import { Platform, StyleSheet } from "react-native";

const titleFont = Platform.select({
  ios: "AvenirNext-DemiBold",
  android: "sans-serif-condensed",
  default: "sans-serif-medium",
});

const bodyFont = Platform.select({
  ios: "AvenirNext-Regular",
  android: "sans-serif",
  default: "sans-serif",
});

export const productDetailStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f8fafc",
  },
  header: {
    backgroundColor: "#ffffff",
    paddingTop: Platform.OS === "android" ? 8 : 6,
    paddingBottom: 8,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
  },
  backButton: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 8,
    backgroundColor: "#f3f4f6",
  },
  backText: {
    color: "#111827",
    fontSize: 18,
    fontWeight: "700",
    fontFamily: titleFont,
  },
  headerTitle: {
    color: "#111827",
    fontSize: 17,
    fontWeight: "800",
    fontFamily: titleFont,
  },
  headerAccent: {
    height: 1,
    backgroundColor: "#e5e7eb",
  },
  content: {
    paddingHorizontal: 14,
    paddingTop: 12,
    paddingBottom: 26,
  },
  productCard: {
    backgroundColor: "#ffffff",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    padding: 12,
    shadowColor: "#0f172a",
    shadowOpacity: 0.08,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
    elevation: 2,
    marginBottom: 12,
  },
  imageWrap: {
    position: "relative",
    borderRadius: 16,
    overflow: "hidden",
    backgroundColor: "#f3f4f6",
    borderWidth: 1,
    borderColor: "#e5e7eb",
    marginBottom: 10,
  },
  imageFavoriteButton: {
    position: "absolute",
    top: 8,
    right: 8,
    zIndex: 10,
    width: 28,
    height: 28,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    backgroundColor: "#ffffff",
    alignItems: "center",
    justifyContent: "center",
  },
  imageFavoriteText: {
    color: "#9ca3af",
    fontSize: 16,
    lineHeight: 18,
    fontFamily: titleFont,
  },
  imageFavoriteTextActive: {
    color: "#f59e0b",
  },
  productImage: {
    width: "100%",
    height: 230,
    resizeMode: "contain",
    backgroundColor: "#f3f4f6",
  },
  titleRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 8,
  },
  nameBlock: {
    flex: 1,
    marginRight: 10,
  },
  productName: {
    fontSize: 34,
    color: "#111827",
    fontWeight: "800",
    marginBottom: 2,
    fontFamily: titleFont,
  },
  productSubtitle: {
    color: "#9ca3af",
    fontSize: 13,
    fontFamily: bodyFont,
  },
  productRating: {
    color: "#f59e0b",
    fontSize: 14,
    marginTop: 4,
    letterSpacing: 0.2,
    fontFamily: bodyFont,
  },
  productPrice: {
    fontSize: 28,
    color: "#111827",
    fontWeight: "800",
    fontFamily: titleFont,
  },
  sectionTitle: {
    color: "#111827",
    fontSize: 24,
    fontWeight: "800",
    marginBottom: 4,
    fontFamily: titleFont,
  },
  descriptionText: {
    fontSize: 13,
    lineHeight: 20,
    color: "#4b5563",
    marginBottom: 10,
    fontFamily: bodyFont,
  },
  inlineMetaRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingTop: 8,
    borderWidth: 1,
    borderColor: "#f3f4f6",
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  inlineMetaLabel: {
    color: "#6b7280",
    fontSize: 12,
    fontWeight: "700",
    fontFamily: titleFont,
  },
  moreCard: {
    backgroundColor: "#ffffff",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 12,
  },
  moreTitle: {
    color: "#111827",
    fontSize: 18,
    fontWeight: "800",
    marginBottom: 8,
    fontFamily: titleFont,
  },
  moreRow: {
    paddingRight: 4,
  },
  moreLoadingBox: {
    width: 120,
    alignItems: "center",
    justifyContent: "center",
  },
  moreEmptyText: {
    color: "#6b7280",
    fontSize: 13,
    fontFamily: bodyFont,
    paddingVertical: 8,
  },
  moreItem: {
    width: 108,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#f3f4f6",
    backgroundColor: "#ffffff",
    marginRight: 8,
    padding: 8,
    position: "relative",
    alignItems: "center",
  },
  moreItemFavoriteButton: {
    position: "absolute",
    top: 6,
    right: 6,
    zIndex: 10,
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    backgroundColor: "#ffffff",
    alignItems: "center",
    justifyContent: "center",
  },
  moreItemFavoriteText: {
    color: "#9ca3af",
    fontSize: 11,
    lineHeight: 13,
    fontFamily: titleFont,
  },
  moreItemFavoriteTextActive: {
    color: "#f59e0b",
  },
  moreItemPressArea: {
    alignItems: "center",
    width: "100%",
  },
  moreItemImage: {
    width: 52,
    height: 52,
    resizeMode: "contain",
    marginBottom: 4,
  },
  moreItemText: {
    color: "#6b7280",
    fontSize: 11,
    fontFamily: bodyFont,
    marginBottom: 2,
  },
  moreItemRating: {
    color: "#f59e0b",
    fontSize: 10,
    marginBottom: 2,
    letterSpacing: 0.1,
    fontFamily: bodyFont,
  },
  moreItemFooter: {
    width: "100%",
    marginTop: 2,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  moreItemPrice: {
    color: "#111827",
    fontSize: 12,
    fontWeight: "700",
    fontFamily: titleFont,
  },
  moreItemCartButton: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 1,
    borderColor: "#d1d5db",
    backgroundColor: "#f8fafc",
    alignItems: "center",
    justifyContent: "center",
  },
  moreItemCartIcon: {
    fontSize: 12,
    lineHeight: 12,
  },
  actionsRow: {
    flexDirection: "row",
    gap: 10,
  },
  addButton: {
    flex: 1,
    backgroundColor: "#ffffff",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    paddingVertical: 13,
    alignItems: "center",
  },
  addButtonDisabled: {
    backgroundColor: "#f3f4f6",
    borderColor: "#e5e7eb",
  },
  addButtonText: {
    color: "#111827",
    fontSize: 16,
    fontWeight: "700",
    fontFamily: titleFont,
  },
  buyNowButton: {
    flex: 1,
    backgroundColor: "#facc15",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#eab308",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 13,
  },
  buyNowDisabled: {
    backgroundColor: "#d1d5db",
    borderColor: "#d1d5db",
  },
  buyNowText: {
    color: "#78350f",
    fontSize: 16,
    fontWeight: "800",
    fontFamily: titleFont,
  },
  feedbackBox: {
    marginTop: 12,
    backgroundColor: "#ecfeff",
    borderWidth: 1,
    borderColor: "#a5f3fc",
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 10,
  },
  feedbackText: {
    fontSize: 13,
    color: "#0e7490",
    textAlign: "center",
    fontFamily: bodyFont,
  },
  feedbackBoxError: {
    backgroundColor: "#fef2f2",
    borderColor: "#fecaca",
  },
  feedbackError: {
    color: "#b91c1c",
  },
});
